### ISSUE TITLE
It needs overall  update

### ISSUE THREAD

**Issue by Mahm0ud-Ahmed** [pinchbv/floor#703] opened 2022-11-07 19:38 UTC

**Comment by dkaera** [comment] 2022-11-07 20:22
@Mahm0ud-Ahmed please add details.

**Comment by Mahm0ud-Ahmed** [comment] 2022-11-07 20:59
> @Mahm0ud-Ahmed please add details.

The most important is that it needs to be integrated with analyzer 5.

**Comment by dkaera** [comment] 2022-11-08 11:53
> > @Mahm0ud-Ahmed please add details.
> 
> The most important is that it needs to be integrated with analyzer 5.

ok, we'll  focus on that next

**Comment by dkaera** [comment] 2022-11-09 07:39
close as a duplicate of #700

**Closed by dkaera** 2022-11-09 07:39 UTC
