### ISSUE TITLE
UPDATE column value Uint8List cause Unhandled Exception

### ISSUE THREAD

**Issue by HXiaoMing** [pinchbv/floor#696] opened 2022-09-13 08:39 UTC
@Entity(tableName: Task.tableName)
class Task {
  static const tableName = 'Task';

  @primaryKey
  final int id;

  final Uint8List data;

  Task(this.id, this.data);

  @override
  String toString() {
    return 'Task{id: $id, len: ${data.length}';
  }
}

@dao
abstract class TaskDao {
  @Query('SELECT * FROM ${Task.tableName} WHERE id = :id')
  Future<Task?> findTaskById(int id);

  @Insert(onConflict: OnConflictStrategy.replace)
  Future<void> insertTask(Task task);

  @Query('UPDATE ${Task.tableName} SET data = :data WHERE id = :id')
  Future<void> updateData(Uint8List data, int id);
}

i want to update table Task column data, data type is Uint8List，database type is blob，after execute TaskDao method updateData，data value change to String！！！

after execute method updateData ,and then  execute TaskDao method findTaskById occur Unhandled Exception

E/flutter (17057): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'String' is not a subtype of type 'Uint8List' in type cast
E/flutter (17057): #0      _$TaskDao.findTaskById.<anonymous closure> (package:floor_issue/issue/database.g.dart:117:48)
E/flutter (17057): #1      QueryAdapter.query (package:floor/src/adapter/query_adapter.dart:30:18)
E/flutter (17057): <asynchronous suspension>
E/flutter (17057): 

source code :  https://github.com/HXiaoMing/floor_new_issue.git

**Comment by HXiaoMing** [comment] 2022-09-13 08:44
![image](https://user-images.githubusercontent.com/22089782/189854998-24963d0f-7cb1-4676-b8c6-7e6c88c3a969.png)

first click insertTask button 

second click updateTask button 

then will occur Unhandled Exception

**Comment by dkaera** [comment] 2022-09-13 08:56
@HXiaoMing  Thank you for reporting the issue. I'll check it today.

**Comment by dkaera** [comment] 2022-09-13 14:27
Good catch @HXiaoMing, as I see, the value for `data` field comes as `String` from `sqflite`, but should be `Uint8List`. Try to check this use case with `sqflite`.

**Comment by dkaera** [comment] 2022-09-13 19:02
Close this issue as a duplicate of #652 
Reopened #652

**Closed by dkaera** 2022-09-13 19:02 UTC
